#This is the Configuration file, edit it to make your custom acheivement messages!
taking-inventory: Good Job!
getting-wood: Good Job!
benchmarking: Good Job!
time-to-mine: Good Job!
acquire-hardware: Good Job!
time-to-farm: Good Job!
bake-bread: Good Job!
hot-topic: Good Job!
the-lie: Good Job!
getting-an-upgrade: Good Job!
delicious-fish: Good Job!
on-a-rail: Good Job!
time-to-strike: Good Job!
monster-hunter: Good Job!
cow-tipper: Good Job!
when-pigs-fly: Good Job!
sniper-duel: Good Job!
diamonds: Good Job!
into-the-nether: Good Job!
return-to-sender: Good Job!
into-fire: Good Job!
local-brewery: Good Job!
enchanter: Good Job!
overkill: Good Job!
librarian: Good Job!
adventuring-time: Good Job!
repopulation: Good Job!
diamonds-to-you: Good Job!
moar-tools: Good Job!
dispense-with-this: Good Job!
leader-of-the-pack: Good Job!
pork-chop: Good Job!
passing-the-time: Good Job!
pot-planter: Good Job!
it's-a-sign: Good Job!
iron-belly: Good Job!
have-a-shearful-day: Good Job!
rainbow-collection: Good Job!
stayin-frosty: Good Job!
chestful-of-cobblestone: Good Job!
renewable-energy: Good Job!
body-guard: Good Job!
iron-man: Good Job!
zombie-doctor: Good Job!
lion-tamer: Good Job!
archer: Good Job!


